import { Globe, Shield, Users } from "lucide-react";

const VisionSection = () => {
  return (
    <section className="py-24 bg-gradient-surface">
      <div className="container mx-auto px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="animate-fade-in-up">
            <h2 className="text-4xl lg:text-5xl font-bold text-foreground mb-8">
              More Than a Tool. 
              <span className="text-transparent bg-gradient-electric bg-clip-text"> It's a New Foundation</span>
            </h2>

            <div className="bg-card border border-border rounded-3xl p-12 shadow-elevated hover:shadow-glow transition-all duration-500">
              {/* Mission statement */}
              <div className="mb-12">
                <p className="text-xl lg:text-2xl text-muted-foreground leading-relaxed mb-8">
                  The Architech is the first product built on 
                  <span className="text-transparent bg-gradient-electric bg-clip-text font-semibold"> AdaptiveProtocols</span>, 
                  our open standards initiative to fight the Technofeudalism of Big Tech.
                </p>
                
                <p className="text-lg text-foreground">
                  Our mission is to build a sovereign digital internet where 
                  <span className="text-transparent bg-gradient-electric bg-clip-text font-semibold"> you own your data</span>. 
                  By using The Architech, you're joining the revolution.
                </p>
              </div>

              {/* Vision pillars */}
              <div className="grid md:grid-cols-3 gap-8">
                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-electric shadow-electric mb-4">
                    <Globe className="h-8 w-8 text-primary-foreground" />
                  </div>
                  <h3 className="text-xl font-semibold text-foreground mb-2">Open Standards</h3>
                  <p className="text-muted-foreground">Building on AdaptiveProtocols for true interoperability</p>
                </div>

                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-electric shadow-electric mb-4">
                    <Shield className="h-8 w-8 text-primary-foreground" />
                  </div>
                  <h3 className="text-xl font-semibold text-foreground mb-2">Data Sovereignty</h3>
                  <p className="text-muted-foreground">You own your code, your data, your future</p>
                </div>

                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-electric shadow-electric mb-4">
                    <Users className="h-8 w-8 text-primary-foreground" />
                  </div>
                  <h3 className="text-xl font-semibold text-foreground mb-2">Developer Freedom</h3>
                  <p className="text-muted-foreground">Breaking free from Big Tech's walled gardens</p>
                </div>
              </div>

              {/* Call to revolution */}
              <div className="mt-12 p-8 bg-gradient-electric rounded-2xl">
                <h3 className="text-2xl font-bold text-primary-foreground mb-4">
                  Join the Revolution
                </h3>
                <p className="text-lg text-primary-foreground/90">
                  Every line of code generated by The Architech is a step toward 
                  a more open, developer-friendly internet. Be part of the change.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default VisionSection;